# Generated by Django 4.1.7 on 2023-04-20 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0006_order'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='registered_user',
        ),
    ]
