# Generated by Django 4.1.7 on 2023-04-26 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_desc', models.CharField(max_length=75)),
                ('price', models.FloatField()),
                ('product_type', models.CharField(max_length=50)),
                ('on_sale', models.BooleanField()),
                ('quantity', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('purchase_date', models.DateField(auto_created=True)),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storefront.product', verbose_name='product_id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.registered_user', verbose_name='user_id')),
            ],
        ),
    ]
