# Generated by Django 4.1.7 on 2023-04-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='uploads/default.jpg', upload_to='uploads/'),
        ),
    ]
