# Generated by Django 4.1.7 on 2023-04-20 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('storefront', '0005_alter_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('purchase_date', models.DateField(auto_created=True)),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storefront.product', verbose_name='product_id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user', verbose_name='user_id')),
            ],
        ),
    ]
